language: node_js

node_js:
  - "4.5.0"

before_install:
  - npm install -g bower
  - npm install -g grunt-cli

install:
  - bower install --save --config.interactive=false
  - npm install

before_script:
  - npm run ci

script:
  - echo -e "run application"
