language: node_js

node_js:
  - "4.5.0"

before_install:
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm install
  - bower install --save --config.interactive=false

before_script:
  - npm run ci

script:
  - echo -e "run application"
